### ISSUE TITLE
베라게임 디자인 템플릿 초안

### ISSUE THREAD

**Issue by helloworld442** [sixteamha/6toyProject#14]

**Comment by Art-mj1** [comment]
<mainpage>

![Image](https://github.com/sixteamha/6toyProject/assets/84562787/a0babc5f-fe81-43b3-9f25-a2b780566866)


<explanationpage>

![Image](https://github.com/sixteamha/6toyProject/assets/84562787/3f10d461-05fc-4709-b45c-cb661d46ee0b)


<firstplayerpage>

![Image](https://github.com/sixteamha/6toyProject/assets/84562787/99bc92a3-4956-4c1d-8f88-adfdad0cbf99)



<gamestartpage>

![Image](https://github.com/sixteamha/6toyProject/assets/84562787/9d7495a5-a422-4c43-90ed-42f32138eb69)



<failpage>

![Image](https://github.com/sixteamha/6toyProject/assets/84562787/417368ac-3d13-416c-a3b5-7fa81a9e0e32)
