### ISSUE TITLE
라이어게임 디자인 템플릿 초안

### ISSUE THREAD

**Issue by helloworld442** [sixteamha/6toyProject#9]

**Comment by hyeon12** [comment]
MainPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/f38fd411-5540-4ad0-98c0-68150d4ed1ef)


expPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/784b6638-3e5c-4f8d-afb9-39e3a5345b19)


gameSelect

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/36025ad0-2b6c-4c19-b5e5-0d6d6e7c018d)


darkPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/9d8a6452-2650-4bcb-8ba5-ab2174f86d46)


liarPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/13762eba-f717-41e7-9900-dc9a27a19f0a)


notLiarPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/2da4d26a-be1d-48bd-b459-c9bb638c791f)


turnPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/f7b73606-7943-47c7-9f6a-30114fe5addb)


liarSelectPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/13a30b87-1980-4f01-964e-b7ce8d4b20a9)


answerPage

![Image](https://github.com/sixteamha/6toyProject/assets/56420106/9e9de30b-2aef-4e82-bd87-9f37290c9d09)
